In [55]:
import numpy as np

In [56]:
#Numpy array filled with 800 numbers ranges from 1 to 100 in 200rows * 4columns
data = np.random.randint(100, size=(200,4))    

In [57]:
#Slicing array into 4 different array

data1 = data[0:49]
data2 = data[50:99]
data3 = data[100:149]
data4 = data[150:199]

print(data1[0])
print(data1[0])

print(data[50])
print(data2[0])

print(data[100])
print(data3[0])

print(data[150])
print(data4[0])

[90 13 36 86]
[90 13 36 86]
[91 65 60 95]
[91 65 60 95]
[95 93  3 84]
[95 93  3 84]
[77 98 28 56]
[77 98 28 56]


In [58]:
#Resshaping sliced arrays into different shapes

data1new = data1.reshape(98,2)
data2new = data2.reshape(49,4)
data3new = data3.reshape(14,14)

print(data1[0])
print(data2[0])
print(data3[0])

[90 13 36 86]
[91 65 60 95]
[95 93  3 84]


In [59]:
#Spliting array horizontally

np.hsplit(data1,2)
np.hsplit(data2,4)



[array([[91],
        [ 2],
        [38],
        [77],
        [ 2],
        [88],
        [73],
        [41],
        [85],
        [44],
        [ 4],
        [11],
        [41],
        [21],
        [97],
        [15],
        [67],
        [80],
        [68],
        [99],
        [91],
        [12],
        [ 3],
        [19],
        [91],
        [45],
        [23],
        [12],
        [67],
        [52],
        [13],
        [17],
        [65],
        [61],
        [19],
        [ 8],
        [95],
        [24],
        [22],
        [32],
        [88],
        [41],
        [43],
        [19],
        [38],
        [12],
        [63],
        [85],
        [89]]),
 array([[65],
        [79],
        [11],
        [24],
        [49],
        [94],
        [81],
        [31],
        [ 4],
        [19],
        [34],
        [21],
        [78],
        [88],
        [61],
        [44],
        [73],
        [ 7],
        [31],
        [63],
        [57],
        [25],
    