In [31]:
import numpy as np

In [32]:
#Numpy array filled with 800 numbers ranges from 1 to 100 in 200rows * 4columns
data = np.random.randint(100, size=(200,4))    

In [33]:
#Slicing array into 4 different array

data1 = data[0:50]
data2 = data[50:100]
data3 = data[100:150]
data4 = data[150:200]

print(data[0])
print(data1[0])

print(data[51])
print(data2[0])

print(data[101])
print(data3[0])

print(data[151])
print(data4[0])

[73  3 70 67]
[73  3 70 67]
[36 64  9 49]
[39 42 15 24]
[83 90 97 72]
[50 23  8 66]
[56 52 72 75]
[ 3 42 18 50]


In [34]:
#Resshaping sliced arrays into different shapes

data1new = data1.reshape(20,10)
data2new = data2.reshape(2,100)
data3new = data3.reshape(100,2)

print(data1new[0])
print(data1new[1])
print(data2new[0])
print(data3new[0])

[73  3 70 67  8 70 98 96  4 21]
[14 44 91 44 60 73 94 95 45 29]
[39 42 15 24 36 64  9 49 44 15 19 28 39 61 31 55 41 89 52 19 70 79 64  7
 99 62 96 98 72 19 68 34 22 88 27 34 36 37 23 94 97 87 28  5 65 96 55 32
 28 65 37 31 53 98 44 12 37  3 64 35 94 38 74 87 50 35 92 30 55 39 34 99
 92  2 23 41 67 55 79  3  1 72 47 99 10 89 79 49 85 81 93 95 62 45 27 23
  7 32 69 35]
[50 23]


In [37]:
#Spliting array horizontally


np.vsplit(data1new,2)
np.hsplit(data3new,2)



[array([[50],
        [ 8],
        [83],
        [97],
        [27],
        [19],
        [32],
        [58],
        [48],
        [87],
        [42],
        [39],
        [55],
        [95],
        [71],
        [89],
        [73],
        [15],
        [10],
        [18],
        [30],
        [86],
        [ 5],
        [24],
        [48],
        [52],
        [63],
        [79],
        [15],
        [ 7],
        [81],
        [34],
        [95],
        [49],
        [90],
        [38],
        [18],
        [20],
        [95],
        [93],
        [89],
        [ 7],
        [10],
        [56],
        [20],
        [86],
        [70],
        [50],
        [45],
        [83],
        [75],
        [23],
        [68],
        [94],
        [ 0],
        [63],
        [74],
        [37],
        [92],
        [50],
        [61],
        [51],
        [81],
        [93],
        [ 6],
        [28],
        [30],
        [ 5],
        [65],
        [ 4],
        [47],
      